### ISSUE TITLE
[Question] Why not using migration to setup the database tables

### ISSUE THREAD

**Issue by longnd** [CuteTN/google-scraper#7]
## Issue

The application uses Drizzle ORM which supports [migration](https://orm.drizzle.team/docs/migrations). Why you decided not to use it to define the DB tables, but [requires running the SQL script manually](https://github.com/CuteTN/google-scraper#database)?

**Comment by CuteTN** [comment]
@longnd I would totally agree that using code-first approach is better in general. However, as this is my first time using NodeJS along with Postgres, I was not really familiar with Drizzle ORM. I decided to keep things simple to avoid unexpected issues and spare time for the main tasks.

**Comment by longnd** [comment]
I understand. Thank you for the explanation.
