### ISSUE TITLE
Insufficient solution to work around Google rate limiting

### ISSUE THREAD

**Issue by longnd** [CuteTN/google-scraper#8]
## Issue
The application implements an in-house queue to process the parsed keywords and workaround Google Rate Limitting by adding a delay between each process.
https://github.com/CuteTN/google-scraper/blob/db67daebccec466a89c86ff17f587b55cb27d29b/server/src/services/google-scraping-scheduler.service.ts#L57-L63

Adding delay is a code smell. Besides that, the current implementation has some limitations
- There is no way to speed up the crawling by running multiple processes. A better way could be using a queue like https://optimalbits.github.io/bull/ to queue the keywords as background jobs and run multiple workers. Also, it saves the effort from re-inventing the queue.
- Rotating the user agents (as you already defined here) to simulate that the requests come from different devices
https://github.com/CuteTN/google-scraper/blob/db67daebccec466a89c86ff17f587b55cb27d29b/server/src/services/google-scraper.service.ts#L10-L13

It is not necessary to open a PR to fix, but I would like to understand why you decided to come up with the current solution?

**Comment by CuteTN** [comment]
@longnd Thank you for the recommendation. As I'm lack of hands-on experience on crawling large data, I'm aware that not every decision I've made here is the best. Despite that, I still tried experimenting my own solution to see how it turned out.

**Comment by longnd** [comment]
Thank you for the explanation. Web scraping is not a common requirement in usual projects. However, it is included in this code challenge to evaluate a developer's ability to come up with a solution and allow us to assess their skills in various criteria.
